### PR TITLE
Sync rebar.config deps with Makefile

### PR DESCRIPTION
**Pull request by leoliu**

### CODE REVIEW

**Comment by essen** [comment]
Actually don't, generate it from the Makefile instead. Add a line like this (with comment): https://github.com/ninenines/cowboy/blob/master/Makefile#L41 and then run `make` and commit what changed.

**Comment by leoliu** [comment]
That's much nice. Thanks.

**Comment by essen** [comment]
Looks good. Will merge soon. Thanks!

**Comment by essen** [comment]
Merged, thanks!

**Pull request closed without merging**
