### PR TITLE
Update to latest erlang.mk

### PR DESCRIPTION
**Pull request by lukebakken**
Includes fix from ninenines/erlang.mk#897'

(cherry picked from commit 7f1e77ec1b75f6c63f11243ea4af27c05052c120)

### CODE REVIEW

**Comment by lukebakken** [comment]
Hi @essen - it would be great to get a new `1.3.x` release with this change. I'll be opening PRs for new point releases for RabbitMQ to use for other libraries, stay tuned.

**Comment by essen** [comment]
Can you confirm whether just updating in Gun is enough, or should the older Cowlib version be updated as well? Gun 1.3.x depends on Cowlib 2.6.0, but I suppose RabbitMQ is actually using a more recent version, at least if you have management or Web plugins.

**Comment by lukebakken** [comment]
Sorry for the delay! Looking at this today.

**Comment by lukebakken** [comment]
Yep, the rest of RabbitMQ is using `cowlib` version `2.7.0`. This PR is updated.

**Comment by essen** [comment]
OK I will release the new version tomorrow then.

**Comment by essen** [comment]
I've merged and pushed so I'm closing this. After confirming this doesn't break anything (who knows) I will push the 1.3.3 tag and ask the Hex package owner to update it.

**Comment by lukebakken** [comment]
OK as soon as 1.3.3 is pushed I can update RabbitMQ. Thanks!

**Comment by essen** [comment]
It's published.

**Pull request closed without merging**
