### PR TITLE
Add support for choosing a process to reply to

### PR DESCRIPTION
**Pull request by manifest**
Aims to [this](https://github.com/ninenines/gun/issues/108) issue.

There is [one case](https://github.com/ninenines/gun/blob/0414eede62946f995a5ab4879f9026548440199c/src/gun_http2.erl?ts=2#L86) when [Owner](https://github.com/ninenines/gun/blob/0414eede62946f995a5ab4879f9026548440199c/src/gun_http2.erl?ts=2#L276) still could receive an `gun_error` message for HTTP2. Because we can't find a particular stream when `connection_error` is occurred, and `StreamID` has't [parsed](https://github.com/ninenines/cowlib/blob/8e6d0f462850a90bd8a60995f52027839288d038/src/cow_http2.erl#L78-L234) yet). The same is for [SPDY](https://github.com/ninenines/gun/blob/0414eede62946f995a5ab4879f9026548440199c/src/gun_spdy.erl?ts=2#L182). I've added a note relating to this behavior to the sources.

As for the tests, it looks like `spdy_SUITE` is broken, and `twitter_SUITE` contains just one testcase. I've added one more testcase to it for now. It will take time to fully cover gun's functionality. Maybe we could merge this PR as is and write testcases as we go?

### CODE REVIEW

**Comment by essen** [comment]
Yes spdy_SUITE has tests for things that are not implemented. I'm considering just dropping SPDY entirely.

**Comment by essen** [comment]
I'd say if there's a connection error, then all processes that have currently emitted a request are supposed to receive a gun_error, no?

**Comment by manifest** [comment]
Good point! It would be match more expected behavior, I believe. I've updated the PR.

**Comment by manifest** [comment]
It also might be useful to pass `ReplyTo :: pid()` to the request function. It allows to redirect response to any process we like. Do we care about backwards compatibility? Could we change arguments of `request/{4,5}` functions, or it would be better to introduce something like `request_to` functions?

```erlang
-spec request(pid(), ReplyTo :: pid(), iodata(), iodata(), headers()) -> reference().
-spec request(pid(), ReplyTo :: pid(), iodata(), iodata(), headers(), iodata()) -> reference().
```

**Comment by essen** [comment]
I would be OK keeping things like this, and adding a function with +1 argument `Opts` that is a map that can have a value `reply_to` that takes a pid that defaults to `self()`. Then nothing breaks, and we have a way to extend things in the future.

**Comment by essen** [comment]
I mean adding a function for each of request, get, post, put...

**Comment by manifest** [comment]
So, instead of

```erlang
-spec post(pid(), iodata(), headers()) -> reference().
-spec post(pid(), iodata(), headers(), iodata()) -> reference().
```

we would have

```erlang
-spec post(pid(), iodata(), headers()) -> reference().
-spec post(pid(), iodata(), headers(), BodyOrOpts) -> reference() when BodyOrOpts :: map().
-spec post(pid(), iodata(), headers(), Body :: iodata(), Opts :: map()) -> reference().
```

Did I get it right?

**Comment by essen** [comment]
Not `BodyOrOpts`, it's easier for users to just write `[]` than to reason about two different argument types. Just the third function.

**Comment by manifest** [comment]
Ok, I got it. Just wonder, what do you think about this variant (to use map for all optional arguments):

```erlang
-type get_request_options() :: #{headers => list(), reply_to => pid()}.
-type put_request_options() :: #{headers => list(), body => iodata(), reply_to => pid()}.

-spec get(pid(), Path :: iodata()) -> reference().
-spec get(pid(), Path :: iodata(), Opts :: get_request_options()) -> reference().

-spec put(pid(), Path :: iodata()) -> reference().
-spec put(pid(), Path :: iodata(), Opts :: put_request_options()) -> reference().

**Comment by essen** [comment]
These aren't options, they're requests with or without extra headers or bodies. It's part of the request, so it shouldn't be hidden like this.

**Comment by manifest** [comment]
Ready. I've also added extended versions of `data/4` and `cancel/2`.

**Comment by essen** [comment]
Let me try to close/reopen to see if it triggers the build.

**Comment by essen** [comment]
Nope. Can I bother you to first: rebase to current master, and then: open a new PR? Thanks.

**Comment by manifest** [comment]
Done.

**Pull request closed without merging**
