### PR TITLE
handle lingering data

### PR DESCRIPTION
**Pull request by tony612**
See https://github.com/ninenines/cowlib/pull/82

### CODE REVIEW

**Comment by tony612** [comment]
@essen Added a test.

**Comment by essen** [comment]
Thanks! Perfect timing as I was probably going to do the same on Monday.

**Comment by tony612** [comment]
Tests failed because of this https://github.com/ninenines/cowboy/pull/1392 And I fixed same issue in this PR.

**Comment by essen** [comment]
Merged, thanks!

**Pull request closed without merging**
