### PR TITLE
Fix gun_http2:handle/2 when goaway is received

### PR DESCRIPTION
**Pull request by edgurgel**
It fixes https://github.com/ninenines/gun/issues/105

I'm not sure if this is correct approach and if I'm following the correct code style. 

I also added 1 eunit test but I'm also not sure what's the correct way to test this case.

### CODE REVIEW

**Comment by essen** [comment]
I think this is the right way to go. I'm not a fan of having eunit tests for this but we don't have a full fledged test server that can send whatever garbage we need yet so that'll do.

**Comment by essen** [comment]
Merged, thanks!

**Comment by edgurgel** [comment]
Yeah I couldn't find a way to test without adding an eunit test. 
Do you have any plans to have a test server? Would it be cowboy or some other implementation? 


Thanks for merging my PR! 🎉

**Comment by essen** [comment]
I wouldn't say "plans" but it'll be necessary at some point. That's the main reason why Gun is lacking in the tests department. And it can't be Cowboy because Cowboy doesn't send garbage.

**Pull request closed without merging**
