### PR TITLE
Fix ws_upgrade to merge argument headers

### PR DESCRIPTION
**Pull request by seizans**
As mentioned at https://github.com/ninenines/gun/issues/63 , I merged `Headers` argument into `Headers2` to be able to set headers.

### CODE REVIEW

**Comment by essen** [comment]
Looks good, thanks. Will merge after EUC.

**Comment by mururu** [comment]
:+1:

**Comment by voluntas** [comment]
:+1:

**Comment by essen** [comment]
Pushed a different fix since I want to avoid ++. Should be good on current master now. Thanks!

**Comment by seizans** [comment]
:+1:

**Pull request closed without merging**
