### PR TITLE
Update to latest erlang.mk

### PR DESCRIPTION
**Pull request by lukebakken**
Includes fix from ninenines/erlang.mk#897'

### CODE REVIEW

**Comment by essen** [comment]
RabbitMQ is using Gun somewhere?

**Comment by lukebakken** [comment]
It is! https://github.com/rabbitmq/rabbitmq-peer-discovery-etcd/blob/master/Makefile

**Comment by essen** [comment]
OK. Good to know!

But note that master is very far from 1.3.x. I am currently working on the remaining changes before I can release a 2.0 rc but this will take the rest of summer at least because it's quite complex (HTTP/2 CONNECT support). So perhaps the best for you would be that I produce an updated 1.3.x release with the most recent Erlang.mk? Alternatively switch RabbitMQ to the current master, many people are already using it with great success. Depends on the expected timeline for this.

**Comment by lukebakken** [comment]
I've been working on the convoluted process to get RabbitMQ into VMware's licensing system and noticed this out-of-date file. I'm re-running the process yet again because _maybe_ we don't need this change? I will know more today. Thanks for bringing that point up.

**Comment by essen** [comment]
Done for master, let me know if needed in older versions. Thanks!

**Pull request closed without merging**
