### PR TITLE
Detect HTTP/1 response to HTTP/2 request and return a specific error

### PR DESCRIPTION
**Pull request by DmitryKakurin**
Fix for #216
Now the error is: `{connection_error, protocol_error, 'HTTP/1 response to HTTP/2 request'}`

### CODE REVIEW

**Comment by DmitryKakurin** [comment]
@essen there are build errors, but I don't think they are caused by my fix. Could you take a look, please?

**Comment by essen** [comment]
Errors are because you have based your branch on 1.3, please base it against master. There's currently no planned 1.x releases unless a customer asks.

**Comment by DmitryKakurin** [comment]
Sorry, that was me clicking on the wrong link.
I've based my fix on 1.3 branch because we are using `gun` indirectly thru `machine_gun`, and it requires version `1.3.*`.
Are you OK with releasing another version off 1.3 branch once I add the check?

**Comment by essen** [comment]
I'm not doing further 1.3 releases unless a customer requests it.

**Comment by DmitryKakurin** [comment]
Are we considered a customer :-) ?
I mean, we are using `gun`, and we need a 1.3 release.

**Comment by essen** [comment]
Paying customer or sponsor.

**Comment by essen** [comment]
Let's continue on the ticket.

**Pull request closed without merging**
